//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputActions/SimulationControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @SimulationControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @SimulationControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""SimulationControls"",
    ""maps"": [
        {
            ""name"": ""Looking"",
            ""id"": ""1baf82ee-cdf0-4809-ae14-71a0e12ef2f9"",
            ""actions"": [
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""098a2db3-0232-4d77-bb22-930f835dfc51"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c1c5f5eb-e4c7-4531-ad3e-39d31b6680d6"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Looking
        m_Looking = asset.FindActionMap("Looking", throwIfNotFound: true);
        m_Looking_Look = m_Looking.FindAction("Look", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Looking
    private readonly InputActionMap m_Looking;
    private ILookingActions m_LookingActionsCallbackInterface;
    private readonly InputAction m_Looking_Look;
    public struct LookingActions
    {
        private @SimulationControls m_Wrapper;
        public LookingActions(@SimulationControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Look => m_Wrapper.m_Looking_Look;
        public InputActionMap Get() { return m_Wrapper.m_Looking; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LookingActions set) { return set.Get(); }
        public void SetCallbacks(ILookingActions instance)
        {
            if (m_Wrapper.m_LookingActionsCallbackInterface != null)
            {
                @Look.started -= m_Wrapper.m_LookingActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_LookingActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_LookingActionsCallbackInterface.OnLook;
            }
            m_Wrapper.m_LookingActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
            }
        }
    }
    public LookingActions @Looking => new LookingActions(this);
    public interface ILookingActions
    {
        void OnLook(InputAction.CallbackContext context);
    }
}
